"""initial schema: all tables from ARCHITECTURE §4 + jobs_fts (FTS5) with sync triggers

Revision ID: 0574c13c842a
Revises:
Create Date: 2026-09-29 10:04:20.118368

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0574c13c842a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_cache",
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("text_hash", name=op.f("pk_ai_cache")),
    )
    op.create_table(
        "category_images",
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("telegram_file_id", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("category", name=op.f("pk_category_images")),
    )
    op.create_table(
        "filter_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("ban", "spam", "scam", name="filterkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("added_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filter_words")),
        sa.UniqueConstraint("word", "kind", name=op.f("uq_filter_words_word_kind")),
    )
    op.create_table(
        "kv_store",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_kv_store")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_seen_id", sa.String(length=255), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("error_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("own_usernames", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("identifier", name=op.f("uq_sources_identifier")),
    )
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("lang", sa.String(length=8), server_default="uz", nullable=False),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("trust_level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("tg_id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=False)

    op.create_table(
        "raw_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("grouped_id", sa.BigInteger(), nullable=True),
        sa.Column("text", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("has_media", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "processing",
                "done",
                "duplicate",
                "not_job",
                "no_text",
                "error",
                name="rawpoststatus",
                native_enum=False,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_posts_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_posts")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_raw_posts_source_id_external_id")
        ),
    )
    with op.batch_alter_table("raw_posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_posts_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_posts_grouped_id"), ["grouped_id"], unique=False)
        batch_op.create_index(
            "ix_raw_posts_status_fetched_at", ["status", "fetched_at"], unique=False
        )

    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("results_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.tg_id"],
            name=op.f("fk_search_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_logs")),
    )
    with op.batch_alter_table("search_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("min_salary", sa.BigInteger(), nullable=True),
        sa.Column("keyword", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.tg_id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("aggregator", "user", name="joborigin", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("raw_post_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=64), server_default="boshqa", nullable=False),
        sa.Column("salary_min", sa.BigInteger(), nullable=True),
        sa.Column("salary_max", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("salary_text", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("is_remote", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("schedule", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("contact_username", sa.String(length=64), nullable=True),
        sa.Column(
            "parse_method",
            sa.Enum(
                "regex",
                "fallback",
                "gemini",
                "form",
                name="parsemethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("formatted_text", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review",
                "queued",
                "sending",
                "retry",
                "published",
                "failed",
                "rejected",
                "closed",
                "expired",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("channel_message_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "origin != 'user' OR contact_phone IS NOT NULL OR contact_username IS NOT NULL",
            name=op.f("ck_jobs_user_job_has_contact"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.tg_id"],
            name=op.f("fk_jobs_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_post_id"],
            ["raw_posts.id"],
            name=op.f("fk_jobs_raw_post_id_raw_posts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_author_id"), ["author_id"], unique=False)
        batch_op.create_index(
            "ix_jobs_category_region_published_at",
            ["category", "region", "published_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_jobs_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_raw_post_id"), ["raw_post_id"], unique=False)
        batch_op.create_index(
            "ix_jobs_status_next_retry_at", ["status", "next_retry_at"], unique=False
        )

    op.create_table(
        "alert_deliveries",
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_alert_deliveries_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_alert_deliveries_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", "job_id", name=op.f("pk_alert_deliveries")),
    )
    with op.batch_alter_table("alert_deliveries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alert_deliveries_job_id"), ["job_id"], unique=False)

    op.create_table(
        "favorites",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_favorites_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.tg_id"],
            name=op.f("fk_favorites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "job_id", name=op.f("pk_favorites")),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favorites_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###

    # --- hand-written: FTS5 keyword search over jobs, kept in sync by triggers -------------
    for sql in JOBS_FTS_UP:
        op.execute(sql)


# Written out literally (not imported from app code) so this migration never changes.
JOBS_FTS_UP = (
    """
    CREATE VIRTUAL TABLE jobs_fts USING fts5(
        title, company, description, city,
        content='jobs', content_rowid='id',
        tokenize='unicode61 remove_diacritics 2'
    )
    """,
    """
    CREATE TRIGGER jobs_fts_ai AFTER INSERT ON jobs BEGIN
        INSERT INTO jobs_fts(rowid, title, company, description, city)
        VALUES (new.id, new.title, new.company, new.description, new.city);
    END
    """,
    """
    CREATE TRIGGER jobs_fts_ad AFTER DELETE ON jobs BEGIN
        INSERT INTO jobs_fts(jobs_fts, rowid, title, company, description, city)
        VALUES ('delete', old.id, old.title, old.company, old.description, old.city);
    END
    """,
    """
    CREATE TRIGGER jobs_fts_au AFTER UPDATE OF title, company, description, city ON jobs BEGIN
        INSERT INTO jobs_fts(jobs_fts, rowid, title, company, description, city)
        VALUES ('delete', old.id, old.title, old.company, old.description, old.city);
        INSERT INTO jobs_fts(rowid, title, company, description, city)
        VALUES (new.id, new.title, new.company, new.description, new.city);
    END
    """,
)

JOBS_FTS_DOWN = (
    "DROP TRIGGER IF EXISTS jobs_fts_au",
    "DROP TRIGGER IF EXISTS jobs_fts_ad",
    "DROP TRIGGER IF EXISTS jobs_fts_ai",
    "DROP TABLE IF EXISTS jobs_fts",
)


def downgrade() -> None:
    """Downgrade schema."""
    for sql in JOBS_FTS_DOWN:
        op.execute(sql)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_job_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("alert_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_deliveries_job_id"))

    op.drop_table("alert_deliveries")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_next_retry_at")
        batch_op.drop_index(batch_op.f("ix_jobs_raw_post_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_fingerprint"))
        batch_op.drop_index("ix_jobs_category_region_published_at")
        batch_op.drop_index(batch_op.f("ix_jobs_author_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_user_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("search_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_search_logs_created_at"))

    op.drop_table("search_logs")
    with op.batch_alter_table("raw_posts", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_posts_status_fetched_at")
        batch_op.drop_index(batch_op.f("ix_raw_posts_grouped_id"))
        batch_op.drop_index(batch_op.f("ix_raw_posts_content_hash"))

    op.drop_table("raw_posts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("sources")
    op.drop_table("kv_store")
    op.drop_table("filter_words")
    op.drop_table("category_images")
    op.drop_table("ai_cache")
    # ### end Alembic commands ###
